version: '3'

volumes:
  sqlite_volume:

services:
  bot_assistant:
    build: /
    restart: always
    volumes:
      - sqlite_volume:/home/db
    environment:
      - TZ=Europe/Moscow
      - BOT_API_TOKEN=
      - TELEGRAM_ACCESS_ID=



